[[commit]]
entry = 7
repository = ".localSpec"
repo_id = "root:.localSpec"
scope = "private"
branch = "ComplexGitSync_memory-dev"
sha = "bfe892c5ec8de509cfcaa103260006deebf0832b"
message = "ticket for clarifying dependencies in the readme, for dummies, and to find the proper granulometry for .memory"
authored_at = "2026-09-17T01:07:29+02:00"

[[published]]
entry = 8
repository = ".localSpec"
sha = "bfe892c5ec8de509cfcaa103260006deebf0832b"
remote = "github:flipoyo/.localSpec"
ref = "refs/heads/ComplexGitSync_memory-dev"
at = "2026-09-16T23:07:40+00:00"
