[[commit]]
entry = 96
repository = ".localSpec"
repo_id = "root:.localSpec"
scope = "private"
branch = "ComplexGitSync"
sha = "8d12b85278bf0a0fc3aa6950820c9574add991db"
message = "merge memory-dev, cgitsync2.77"
authored_at = "2026-09-17T22:12:21+02:00"

[[published]]
entry = 97
repository = ".localSpec"
sha = "8d12b85278bf0a0fc3aa6950820c9574add991db"
remote = "github:flipoyo/.localSpec"
ref = "refs/heads/ComplexGitSync"
at = "2026-09-17T20:12:42+00:00"
