format_version = 1
environment_root = ""
credentials = [
    { provider = "github", tool = "gh", available = false, authenticated = false },
]

[machine]
architecture = "x86_64"
pixi_platform = "linux-64"
os_name = "ubuntu"
os_version = "24.04"
libc_name = "glibc"
libc_version = "2.39"
kernel_release = "6.8.0-139-generic"

[[tools]]
name = "cgitsync"
raw = "3.1.6"
version = "3.1.6"

[[tools]]
name = "dvc"
raw = "none"
version = "none"

[[tools]]
name = "gh"
raw = "none"
version = "none"

[[tools]]
name = "git"
raw = "git version 2.43.0"
version = "2.43.0"

[[tools]]
name = "git-lfs"
raw = "none"
version = "none"

[[tools]]
name = "pixi"
raw = "pixi 0.66.0"
version = "0.66.0"

[[tools]]
name = "python"
raw = "3.11.15"
version = "3.11.15"

[[tools]]
name = "ssh"
raw = "OpenSSH_9.6p1 Ubuntu-3ubuntu13.19, OpenSSL 3.0.13 30 Jan 2024"
version = "9.6"

[[manifests]]
repository = "root"
path = "pixi.lock"
digest = "sha256:c6861715323ab300b2f3eabc6f0194e3f0840bb7b228845ec2463f3d0d513d72"
platforms = [
    "linux-64",
    "osx-arm64",
    "win-64",
]

[[manifests]]
repository = "root"
path = "pixi.toml"
digest = "sha256:08754ac75674a2c016528efb618df1d98f02538d6e1e10034731c0b4b3432f5e"
platforms = []

[[manifests]]
repository = "root"
path = "pyproject.toml"
digest = "sha256:83a6df00c76ce80e494c077c09db61126ef0a8a79123deecbf8b41c9466d5319"
platforms = []
